BMS-dotnet-WebApplication/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using BMS.BooksLibrary.BusinessLayer;
using BMS.BooksLibrary.BusinessLayer.Models;
using BMS.BusinessLayer;
using BMS.BusinessLayer.Constant;
using BMS.BusinessLayer.Library.Models;
using BMS_dotnet_WebApplication.Models.LibraryVM;
using BMS_dotnet_WebApplication.Models.UserVM;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using static Newtonsoft.Json.JsonConvert;

namespace BMS_dotnet_WebApplication.Controllers
{
    public class LibraryController : BaseController
    {
        private const string BooksImagesFolder = "booksimg";
        private readonly Random _random;
        private List<BooksCategoryModel> _booksCategories;
        private readonly IBooksLibraryManager _booksLibraryManager;
        private readonly ICacheManager _cacheManager;
        private readonly IMapper _mapper;
        private readonly Random _rnd;
        private readonly IEmailManager _emailManager;

        public LibraryController(IBooksLibraryManager booksLibraryManager, ICacheManager cacheManager, IMapper mapper, IEmailManager emailManager)
        {
            _random = new Random();
            _booksLibraryManager = booksLibraryManager;
            _cacheManager = cacheManager;
            _mapper = mapper;
            _rnd = new Random();
            _emailManager = emailManager;

            ViewBag.IsItLibrary = true;
        }

        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(LoggedInName()))
                return RedirectToAction("Login", "User");

            return View();
        }

        public async Task<IActionResult> BooksCategory()
        {
            if (string.IsNullOrEmpty(LoggedInName())|| !IsAllowed(UserLevel.AccessArea.LibraryAdmin))
                return RedirectToAction("Login", "User");

            _booksCategories = await GetBooksCategories();

            var model = new AdminBooksCategoryVM
            {
                BooksCategory = new BooksCategoryVM(),
                ExistingCategories = _booksCategories
            };
            return View(model);
        }

        public async Task<IActionResult> RegisterBook()
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.LibraryAdmin))
                return RedirectToAction("Login", "User");

            _booksCategories = await GetBooksCategories();
            var model = new RegisterBookVM
            {
                Categories = _booksCategories.Select(g => new SelectListItem {Text = g.Name, Value = g.CategoryId}).ToList(),
                NewsBooks = await GetBooks()
            };

            return View(model);
        }

        public async Task<ActionResult> AddCategory(IFormCollection collection)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("BooksCategory");

            var newCategory = new BooksCategoryModel
            {
                Name = collection["BooksCategory.Name"],
                Comment = collection["BooksCategory.Comment"],
                CategoryId = _random.Next(1001, 9999).ToString()
            };

            if (_booksCategories == null) _booksCategories = await GetBooksCategories();
            _booksCategories.Add(newCategory);
            _cacheManager.Set("BooksCategories", _booksCategories);

            return RedirectToAction("BooksCategory");
        }

        public async Task<ActionResult> AddBooks(RegisterBookVM model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("BooksCategory");

            var bookModel = _mapper.Map<BookModel>(model);
            bookModel.BookCategory = new BooksCategoryModel
            {
                Name = model.SelectedCategoryText,
                CategoryId = model.SelectedCategory
            };
          

            var cachedBooks = await GetBooks();
            cachedBooks.Add(bookModel);
            if (!string.IsNullOrEmpty(model.MainImageFileName?.FileName))
            {
                bookModel.MainImageFileName = model.MainImageFileName.FileName;
                await SaveBookImage(model.MainImageFileName);
            }

            _cacheManager.Set("LibraryBooks", cachedBooks);

            return RedirectToAction("RegisterBook");
        }

        public ActionResult Save()
        {
            var cachedBooksCategories = _cacheManager.Get<List<BooksCategoryModel>>("BooksCategories");
            var s3 = UpdateCategoryInS3(cachedBooksCategories).Result;

            return RedirectToAction("Index", "User");
        }

        public ActionResult SaveBook()
        {
            var cachedBooksCategories = _cacheManager.Get<List<BookModel>>("LibraryBooks");
            foreach (var book in cachedBooksCategories) book.IsAvailable = true;

            var s3 = SaveBooksInS3(cachedBooksCategories).Result;
            if (s3)
                _cacheManager.RemoveCache("LibraryBooks");
            return RedirectToAction("Index","User");
        }

        public async Task<IActionResult> SearchBook()
        {
            _booksCategories = await GetBooksCategories();
            var model = new SearchForBookVM
            {
                Categories = _booksCategories.Select(g => new SelectListItem {Text = g.Name, Value = g.CategoryId}).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SearchBook(SearchForBookVM model)
        {
            _booksCategories = await GetBooksCategories();
            model.SearchedResult = await SearchFromBooks(model);
            model.Categories = _booksCategories.Select(g => new SelectListItem {Text = g.Name, Value = g.CategoryId}).ToList();

            return View(model);
        }

        public async Task<IActionResult> LendingRequest()
        {
            if (string.IsNullOrEmpty(LoggedInName()))
                return RedirectToAction("Login", "User");

            var basket = HttpContext.Session.GetString(LoggedInName());

            if (string.IsNullOrEmpty(basket))
                return RedirectToAction("SearchBook");

            var books = DeserializeObject<List<BookModel>>(basket);

            await _booksLibraryManager.BookLendingRequest(BuildLendingRequest(books));

            var getFromSession = GetUserProfile();
            getFromSession?.BookLendingRequests?.Add(BuildLendingRequest(books));
            var str = JsonConvert.SerializeObject(getFromSession);
            HttpContext.Session.SetString("userProfile", str);

            return RedirectToAction("Index", "User");
        }

        public async Task<IActionResult> LentOutRequest(bool isRequest)
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.LibraryAdmin))
                return RedirectToAction("Login", "User");
            
            var model = new List<LendingRequestModel>(); 

            if (GetUserProfile().BookLendingRequests.Any())
            {
                model = GetUserProfile().BookLendingRequests;
            }
            else
            {
                model = await _booksLibraryManager.GetNewLendingRequests();
            }

            model = isRequest ? model.Where(r => r.LentOn == null).ToList() : model.Where(r => r.LentOn != null).ToList();

            ViewBag.isRequest = isRequest;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> LentOut(LendingRequestModel model)
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.LibraryAdmin))
                return RedirectToAction("Login", "User");

            var userPf = GetUserProfile();

            var lendingOutRequest = userPf.BookLendingRequests.FirstOrDefault(r => r.LendingRequestId == model.LendingRequestId);
            lendingOutRequest.LentOn = model.LentOn;
            lendingOutRequest.LentBy = userPf.Name;
            lendingOutRequest.Note = model.Note;
            lendingOutRequest.ReturnedOn = model.ReturnedOn;
            lendingOutRequest.IsReadyToCollect = model.IsReadyToCollect;

            if (model.LentOn != null)
            {
                userPf.BookLendingRequests = userPf.BookLendingRequests.Where(r => r.LendingRequestId != model.LendingRequestId).ToList();
            }
            
            if (model.ReturnedOn != null)
            {
                userPf.BookLendingRequests.Add(lendingOutRequest);
            }

            try
            {
                await _booksLibraryManager.BookLendingOut(lendingOutRequest);

                var str = SerializeObject(userPf);
                HttpContext.Session.SetString("userProfile", str);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return RedirectToAction("Index", "User");
        }

        private LendingRequestModel BuildLendingRequest(List<BookModel> basket)
        {
            var getUserProfile = GetUserProfile();
            return new LendingRequestModel
            {
                LendingRequestId = _rnd.Next(1, 99999),
                RequestedBy = getUserProfile.Name,
                RequestedEmail = getUserProfile.Email,
                PhoneNo = getUserProfile.PhoneNo,
                RequestedDate = DateTime.Today,
                BooksLent = basket
            };
        }

        public int AddBooksToCart(BookModel model)
        {
            if (string.IsNullOrEmpty(LoggedInName()))
                return 0;

            var loggedInName = LoggedInName();

            var basketJson = HttpContext.Session.GetString(loggedInName);
            var basket = new List<BookModel>();
            if (!string.IsNullOrWhiteSpace(basketJson))
            {

BMS-dotnet-WebApplication/Views/Library/BooksCategory.cshtml
@model BMS_dotnet_WebApplication.Models.LibraryVM.AdminBooksCategoryVM

@{
    ViewData["Title"] = "Books Genre";
}

<h1>Register new Books Genre</h1>

@using (Html.BeginForm("AddCategory", "Library", FormMethod.Post, new { @id = "partialform" }))
{
   
        <div class="form-group">
            @Html.LabelFor(m => m.BooksCategory.Name)
            @Html.TextBoxFor(m => m.BooksCategory.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.BooksCategory.Name)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.BooksCategory.Comment)
            @Html.TextBoxFor(m => m.BooksCategory.Comment, new { @class = "form-control" })
            
        </div>
        <div class="form-group ">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>

        @*</div>
            <div class="form-group row container">*@
        <div class="col-sm-12">
            <ul>
                <li>
                    Books Categories
                    <ul>
                        @foreach (var category in Model.ExistingCategories)
                        {
                            <li>
                                @category.Name -- @category.Comment
                            </li>
                        }
                    </ul>
                </li>
            </ul>
        </div>
        <div class="form-group">
            @Html.ActionLink("Save", "Save", "Library", null, new { @class = "btn btn-success" })
        </div>
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
}

BMS-dotnet-WebApplication/Views/Library/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="form-group row container custom-box">
    @Html.ActionLink("Books Categories", "BooksCategory", "Library", null, new { @class = "btn btn-success" })
</div>
<div class="form-group row container custom-box">
    @Html.ActionLink("Register Books", "RegisterBook", "Library", null, new { @class = "btn btn-success" })
</div>

<div class="form-group row container custom-box">
    @Html.ActionLink("Book Search", "SearchBook", "Library", null, new { @class = "btn btn-success" })
</div>

BMS-dotnet-WebApplication/Views/Library/LentOutRequest.cshtml
@model List<BMS.BusinessLayer.Library.Models.LendingRequestModel>

@{
    var isRequest =(bool)ViewBag.isRequest;
    var Id = 0;
    var DueNow = "";

}
<h1>Books lent out request</h1>
<div id="accordion">
    @foreach (var bookRequest in Model)
    {
        Id = Id + 1;
        DueNow = DateTime.Today > bookRequest.LentOn?.AddDays(14) ? "DueNow" : "";

        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link accordClick " id=@($"{Id}") data-toggle="collapse" data-target=@($"{"#collapse"}{Id}") aria-expanded="true" aria-controls=@($"{"collapse"}{Id}")>
                       @if (isRequest)
                       {
                        <span> @bookRequest.RequestedBy has requested for @bookRequest.BooksLent.Count Books</span>
                       }
                       else
                       {
                          <span class="@DueNow">  @bookRequest.BooksLent.Count Books have been lent to @bookRequest.RequestedBy</span>
                       }

                    </button>
                </h5>
            </div>

            <div id=@($"{"collapse"}{Id}") class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    @using (Html.BeginForm("LentOut", "Library", FormMethod.Post))
                    {
                        <div class="form-group row">
                            @foreach (var t in bookRequest.BooksLent)
                            {

                                <div class="float-left">
                                    @Html.Partial("_BookCard", t)
                                </div>

                            }
                        </div>

                        <div class="form-group row">
                            <div class="col-md-4">
                                @Html.Label($"LentOn{Id}", "Lent On")
                                @Html.TextBox($"LentOn{Id}", GetDate(bookRequest.LentOn), new { @class = $"form-control LentOn", autocomplete = "off" })

                            </div>
                            <div class="col-md-4">
                                @Html.Label($"ReturnedOn{Id}", "Returned On")
                                @Html.TextBox($"ReturnedOn{Id}", "", new { @class = $"form-control ReturnedOn", autocomplete = "off" })

                            </div>
                        </div>
                        <div class="form-check">
                            @Html.CheckBox("IsReadyToCollect", @bookRequest.IsReadyToCollect, new { @class = "form-check-input" })
                            <label class="form-check-label" for="IsReadyToCollect">Ready to Collect</label>
                        </div>
                        <div class="form-group">
                            @Html.Label("Note", "Note")
                            @Html.TextArea("Note", @bookRequest.Note, new { @class = "form-control" })
                        </div>
                        @Html.Hidden("RequestedBy", bookRequest.RequestedBy)
                        @Html.Hidden("RequestedBy", bookRequest.RequestedBy)
                        @Html.Hidden("RequestedEmail", bookRequest.RequestedEmail)
                        @Html.Hidden("LendingRequestId", bookRequest.LendingRequestId)
                        @Html.Hidden("LentOn", "")
                        @Html.Hidden("ReturnedOn", "")

                        <button type="submit" class="btn btn-primary submit">Register</button>
                        @Html.ActionLink("Send Email Reminder", "SendEmailRemainder", "Library", new { Id = bookRequest.LendingRequestId, email= bookRequest.RequestedEmail }, new { @class = "btn btn-danger" })



                    }
                </div>
            </div>
        </div>
    }
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial"/>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
       

        $('.accordClick').click(function() {
           
            var id = $(this).attr("id");

            $("#LentOn" + id).datepicker({
                dateFormat: 'dd-M-yy'
            });

            $("#ReturnedOn" + id).datepicker({
                dateFormat: 'dd-M-yy'
            });

        });

        $('.submit').click(function() {
            $(this).parent().find("#LentOn").val($(this).parent().find('.LentOn').val());
            $(this).parent().find("#ReturnedOn").val($(this).parent().find('.ReturnedOn').val());
        });
    </script>
}

@functions{

    private string GetDate(DateTime? date)
    {
        if (date == null)
            return null;

        var date1 = (DateTime) date;
        return date1.ToString("dd-M-yy");

        
    }
}

BMS-dotnet-WebApplication/Views/Library/RegisterBook.cshtml
@model BMS_dotnet_WebApplication.Models.LibraryVM.RegisterBookVM
@{
    ViewData["Title"] = "Register Book";
}

<h1>Register Book</h1>

@using (Html.BeginForm("AddBooks", "Library", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.SelectedCategory)
        @Html.DropDownListFor(m => m.SelectedCategory, Model.Categories, "Select Category", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.SelectedCategory)
        @Html.HiddenFor(m => m.SelectedCategoryText)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Barcode)
        @Html.TextBoxFor(m => m.Barcode, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Barcode)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.NumberOfCopies)
        @Html.TextBoxFor(m => m.NumberOfCopies, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.NumberOfCopies)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Publisher)
        @Html.TextBoxFor(m => m.Publisher, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Location)
        @Html.TextBoxFor(m => m.Location, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Comments)
        @Html.TextBoxFor(m => m.Comments, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Register</button>
    </div>

    @if (Model.NewsBooks.Any())
    {
        @foreach (var book in Model.NewsBooks)
        {
            <div class="float-left">
                @Html.Partial("_BookCard", book)
            </div>
        }

        <div class="form-group marginT32">
            @Html.ActionLink("Save", "SaveBook", "Library", null, new { @class = "btn btn-success" })
        </div>
    }
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script>
        $("#SelectedCategory").on("change",
            function () {
                $("#SelectedCategoryText").val($(this).find("option:selected").text());
            });
    </script>

}

BMS-dotnet-WebApplication/Views/Library/SearchBook.cshtml
@model BMS_dotnet_WebApplication.Models.LibraryVM.SearchForBookVM
@{
    ViewData["Title"] = "Search Book";
}

<h1>Search for Books</h1>

@using (Html.BeginForm("SearchBook", "Library", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(m => m.CategoryName)
        @Html.DropDownListFor(m => m.Categories, Model.Categories, "Select Category", new { @class = "form-control" })
       
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Barcode)
        @Html.TextBoxFor(m => m.Barcode, new { @class = "form-control" })
        @Html.HiddenFor(m => m.CategoryName)
           
       
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
       
    </div>
    
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Search</button>
    </div>


    @if (Model.SearchedResult !=null && Model.SearchedResult.Any())
    {
        foreach (var book in Model.SearchedResult)
        {

            <div class="float-left">
                @Html.Partial("_BookCard", book)
            </div>


        }
       
    }


    <div class="form-group" id="divBookSelected">
        <a class="btn btn-success" asp-area="" asp-controller="Library" asp-action="LendingRequest">Books Selected <span class="badge badge-light booksCount">0</span></a>
    </div>
    

@section Scripts
{
   
    <script>
        $("#Categories").on("change", function () {
            $("#CategoryName").val($(this).find("option:selected").text());
        });
    </script>

}

}