BMS-dotnet-WebApplication/Models/Shared/FeedbackModel.cs
using System.ComponentModel.DataAnnotations;

namespace BMS_dotnet_WebApplication.Models.Shared
{
    public class FeedbackModel
    {
        public string FeedbackOn { get; set; }

        [Display(Name="Name")]
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Please Enter a valid email address")]
        public string EmailAddress { get; set; }

        [Display(Name = "Feedback")]
        [Required(ErrorMessage = "Feedback cannot be empty")]
        public string FeedBack { get; set; }
    }
}

BMS-dotnet-WebApplication/Controllers/FeedBackController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using BMS.BusinessLayer;


namespace BMS_dotnet_WebApplication.Controllers
{
    
    public class FeedBackController : Controller
    {
        private readonly IFeedBack _feedBack;
        private readonly IMapper _mapper;

        public FeedBackController(IFeedBack feedBack,IMapper mapper)
        {
            _feedBack = feedBack;
            _mapper = mapper;

        }

        public async Task<ActionResult> Index()
        {
            var feedback = await _feedBack.ReadFeedBak();

            return View(feedback);
        }
    }
}

BMS-dotnet-WebApplication/Controllers/MagazineController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using BMS.BooksLibrary.BusinessLayer;
using BMS.BusinessLayer;
using BMS.BusinessLayer.Constant;
using BMS.BusinessLayer.Magazine;
using BMS.BusinessLayer.Magazine.Models;
using BMS_dotnet_WebApplication.Models.MagazineVM;
using BMS_dotnet_WebApplication.Models.Shared;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMS_dotnet_WebApplication.Controllers
{
    public class MagazineController : BaseController
    {
        private List<MagazineCategory> _magazineCategories;
        private readonly IMagazineManager _magazineManager;
        private readonly ICacheManager _cacheManager;
        private readonly IMapper _mapper;
        private readonly IEmailManager _emailManager;
        private readonly IFeedBack _feedBack;
        private readonly Random _rnd;

        private const string CategoryCacheKey = "MagazineCategories";
        private const string BaseUrl = "http://www.magazine.britanniaislamiccentre.org/";
        private const string CategoryIconFolder = "magazinecategoryicon";

        public MagazineController(IMagazineManager magazineManager, ICacheManager cacheManager, IMapper mapper, IEmailManager emailManager, IFeedBack feedbak)
        {
            _mapper = mapper;
            _magazineManager = magazineManager;
            _cacheManager = cacheManager;
            _emailManager = emailManager;
            _feedBack = feedbak;
            _rnd = new Random();
        }

        public async Task<IActionResult> Index()
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.MagazineAdmin))
                return RedirectToAction("Login", "User");

            var model = await BuildIndexVM();

            return View(model);
        }

        public async Task<IActionResult> CreateCategory()
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.MagazineAdmin))
                return RedirectToAction("Login", "User");

            var model = new MagazineCategoriesVM
            {
                AddMagazineCategory = new MagazineCategoryVM(),
                ExistingCategories = await GetListOfCategories()
            };

            return View(model);
        }

        public async Task<IActionResult> CurrentEdition(string Id = "CurrentEdition")
        {
            var model = await GetCurrentMagazine(Id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory(MagazineCategoryVM model)
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.MagazineAdmin))
                return RedirectToAction("Login", "User");

            if (!ModelState.IsValid)
                return RedirectToAction("CreateCategory");

            var result = await SaveMagazineImage(model.IconImage, CategoryIconFolder);

            var newCategory = new MagazineCategory
            {
                Name = model.Name,
                CategoryId = _rnd.Next(1001, 9999).ToString(),
                Order = model.Order,
                IconImage = model.IconImage.FileName
            };

            if (_magazineCategories == null) _magazineCategories = await GetListOfCategories();
            _magazineCategories.Add(newCategory);
            _cacheManager.Set(CategoryCacheKey, _magazineCategories);

            return RedirectToAction("CreateCategory");
        }

        public async Task<IActionResult> SaveCategories()
        {
            var cachedMagazineCategories = _cacheManager.Get<List<MagazineCategory>>(CategoryCacheKey);
            var s3 = await _magazineManager.SaveMagazineCategories(cachedMagazineCategories);

            return RedirectToAction(s3 ? "Index" : "CreateCategory");
        }

        public IActionResult CreateMagazine()
        {
            var model = new MagazineVM
            {
                CreatedBy = LoggedInName(),
                CreatedDate = DateTime.Now
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateMagazine(MagazineVM model)
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.MagazineAdmin))
                return RedirectToAction("Login", "User");

            if (!ModelState.IsValid)
                return View(model);

            var folderName = model.MagazineName.Replace(" ", "");
            var result = await SaveMagazineImage(model.MainImage, folderName)
                .ConfigureAwait(false);

            var magazine = new Magazine
            {
                Name = model.MagazineName,
                CreatedBy = HttpContext.Session.GetString("Name"),
                DateCreated = DateTime.Now,
                Image = model.MainImage.FileName,
                FolderName = folderName,
                MagazineId = _rnd.Next(1001, 9999).ToString()
            };

            await _magazineManager.CreateMagazine(magazine);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> CreateContent(string Id)
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.MagazineAdmin))
                return RedirectToAction("Login", "User");

            var categories = await GetListOfCategories();
            var model = new MagazineContentVM
            {
                NewsCategories = categories.Select(c => new SelectListItem { Text = c.Name, Value = c.CategoryId.ToString() }).ToList(),
                CreatedDate = DateTime.Today.ToString("d"),
                EnteredBy = HttpContext.Session.GetString("Name"),
                Magazine = new MagazineVM { MagazineId = Id }
            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreateContent(MagazineContentVM model)
        {
            if (string.IsNullOrEmpty(LoggedInName()) || !IsAllowed(UserLevel.AccessArea.MagazineAdmin))
                return RedirectToAction("Login", "User");

            var currentEdition = await _magazineManager.GetMagazine(model.Magazine.MagazineId);

            var magazineContentModel = new MagazineContent
            {
                AuthoredBy = model.Author,
                Body = model.NewsBody,
                Category = new MagazineCategory { CategoryId = model.CategoryId },
                EnteredBy = HttpContext.Session.GetString("Name"),
                EnteredDate = DateTime.Today.ToString(),
                Heading = model.Heading,
                Index = model.Index,
                ContentId = _rnd.Next(0, 99999).ToString(),
                MagazineId = currentEdition.MagazineId,
                FolderName = currentEdition.FolderName
            };

            var stringImages = new List<string>();

            if (model.MainImage != null)
            {
                magazineContentModel.MainImage = model.MainImage.FileName;
                await SaveMagazineImage(model.MainImage, currentEdition.FolderName);
            }
            else
            {
                stringImages.Add("thumbnail.jfif");
            }

            if (model.SubImage1 != null)
            {
                magazineContentModel.SubImage1 = model.SubImage1.FileName;
                await SaveMagazineImage(model.SubImage1, currentEdition.FolderName);
            }

            if (model.SubImage2 != null)
            {
                magazineContentModel.SubImage2 = model.SubImage2.FileName;
                await SaveMagazineImage(model.SubImage2, currentEdition.FolderName);
            }

            if (model.SubImage3 != null)
            {
                magazineContentModel.SubImage3 = model.SubImage3.FileName;
                await SaveMagazineImage(model.SubImage3, currentEdition.FolderName);
            }

            if (model.SubImage4 != null)
            {
                magazineContentModel.SubImage4 = model.SubImage4.FileName;
                await SaveMagazineImage(model.SubImage4, currentEdition.FolderName);
            }

            if (model.SubImage5 != null)
            {
                magazineContentModel.SubImage5 = model.SubImage5.FileName;
                await SaveMagazineImage(model.SubImage5, currentEdition.FolderName);
            }

            magazineContentModel.YouTubLink = model.YouTubLink;

            await _magazineManager.AddMagazineContent(magazineContentModel);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(string id, string mid)
        {
            var model = await GetMagazineContent(id, mid);

            return View(model);
        }

        public async Task<string> GetCurrentEditionImg()
        {
            var magazine = await _magazineManager.GetCurrentEdition();
            return $"{BaseUrl}/{magazine.FolderName}/{magazine.Image}";
        }

        public async Task<ActionResult> StatusUpdate(bool status, string id)
        {
            await _magazineManager.UpdateMagazineStatus(status, id);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> RemoveContent(string Id)
        {
            var magazine = await _magazineManager.GetMagazine(Id);
            var model = _mapper.Map<RemoveMagazineVM>(magazine);
            model.RemoveContentId = new List<string>();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveContent(string MagazineId, string RemoveContentId)
        {
            var contentIdsToRemove = RemoveContentId.Split(",");
            var magazine = await _magazineManager.RemoveContentsFromCurrentEdition(MagazineId, contentIdsToRemove);

BMS-dotnet-WebApplication/Views/Shared/_BookCard.cshtml
@model BMS.BooksLibrary.BusinessLayer.Models.BookModel

<div class="card card-book">
    @if (!string.IsNullOrEmpty(Model.MainImageFileName))
    {
        <div class="book-card-img">
            <img src="@Url.Action("GetImage", new {filename = "booksimg/" + Model.MainImageFileName})" style="height: 125px;" alt="...">
        </div>
    }
<div class="card-body" id="@Model.Barcode">
    <h5 class="card-title"> @Model.Title</h5>
    @if (Model.BookCategory != null)
    {
        <p class="card-text">Category : @Model.BookCategory.Name</p>
    }
    <p class="card-text">Barcode : @Model.Barcode</p>
    @if (!string.IsNullOrEmpty(Model.Description))
    {
        <p class="card-text">Description : @Model.Description</p>
    }
    @if (!string.IsNullOrEmpty(Model.Comments))
    {
        <p class="card-text">Comment : @Model.Comments</p>
    }
    @if (!string.IsNullOrEmpty(Model.Publisher))
    {
        <p class="card-text">Publisher : @Model.Publisher</p>
    }
    <p class="card-text"> location : @Model.Location</p>
    @if (Model.IsAvailable)
    {
        <a href="#" class="btn btn-primary" onclick="addToBucket(@Model.Barcode)">Add to Basket</a>

        <input type="hidden" id="_BookTitle_@Model.Barcode" name="_BookTitle_@Model.Barcode" value="@Model.Title" />
        <input type="hidden" id="_BookBarcode_@Model.Barcode" name="_BookBarcode_@Model.Barcode" value="@Model.Barcode" />
        <input type="hidden" id="_BookImage_@Model.Barcode" name="_BookImage_@Model.Barcode" value="@Model.MainImageFileName" />
    }

</div>
</div>

<script>
    function addToBucket(barcode) {
        $.post("/Library/AddBooksToCart",
            {
                Title: $('#_BookTitle_' + barcode).val(),
                Barcode: $('#_BookBarcode_' + barcode).val(),
                MainImageFileName: $('#_BookImage_' + barcode).val()
            },
            function(data) {

                $(".booksCount").text(data);
                $("#divBookSelected").css("display", "block");;

            });
    };

</script>

BMS-dotnet-WebApplication/Views/Shared/_Feedback.cshtml
@model BMS_dotnet_WebApplication.Models.Shared.FeedbackModel


@using (Html.BeginForm("Feedback", "Magazine", FormMethod.Post))
{
    <div class="feedback">
        <div class="feedback-info">
            Your feedback helps us give you our best content. Please take a moment to leave your feedback, suggestions and ideas that you would like us to include in our future issues. <br />
            To get in touch, we can be reached via editor-magazine@britanniaislamiccentre.org  <br />
            Thank You!
        </div>
        <div>
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        </div>

        @Html.HiddenFor(m => m.FeedbackOn)

        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.EmailAddress)
            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.EmailAddress)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.FeedBack)
            @Html.TextAreaFor(m => m.FeedBack, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FeedBack)
        </div>

        <div class="form-group">
            <button type="submit" id="btnSubmit" class="btn btn-primary">Submit</button>
        </div>
    </div>
}

BMS-dotnet-WebApplication/Views/Shared/_Layout.cshtml
@{
    // var isLibrary = ViewBag.IsItLibrary;
    var isLibrary = Context.Request.Host.ToString().Contains("localhost",StringComparison.OrdinalIgnoreCase) ||
     Context.Request.Host.ToString().Contains("bic-library", StringComparison.OrdinalIgnoreCase) ;
   
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @RenderSection("Meta", required: false)

    @if (isLibrary)
    {
        <title>Bic Library - @ViewData["Title"] </title>
    }
    else
    {
        <title>The Soul Journal - @ViewData["Title"] </title>
    }


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/quill.css" />
    @if (isLibrary)
    {
        <link rel="stylesheet" href="~/css/bicLibrary.css" />
    }
    else
    {
        <link rel="stylesheet" href="~/css/magazine.css" />
    }

    <link rel="SHORTCUT ICON" href="~/imgs/TabIcone1.png" type="image/x-icon" />
    <link rel="ICON" href="~/imgs/TabIcone1.png" type="image/ico" />

</head>
<body class="bg-site">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-magazine border-bottom box-shadow mb-3">
            <div class="container container-bg">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (isLibrary)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/imgs/bic-Library.png" /></a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Magazine" asp-action="CurrentEdition">Magazine</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">My Account</a>
                                </li>*@
                        </ul>


                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/imgs/logo.png" /></a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Magazine" asp-action="CurrentEdition">Magazine</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">My Account</a>
                                </li>*@
                        </ul>

                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BMS-dotnet-WebApplication/Views/Shared/_MagazineCard.cshtml
@model BMS.BusinessLayer.Magazine.Models.MagazineContent
@{
    ViewData["Title"] = "_MagazineCard";
}

<div class="card-Magazine" >
    <a href='@Url.Action("Details", "Magazine", new {Id = Model.ContentId, mid= Model.MagazineId})' class="magazin-card-link">
        <div class="card-img">
            <img class="center" style="max-height: 175px;" src="@Url.Action("GetImage", new {filename = $"{Model.FolderName}/{Model.MainImage}", section = "magazine"})" alt="...">
        </div>
        <div class="card-body magazin-card-body">
            <h5 class="card-title">@Html.DisplayFor(m => m.Heading)</h5>
            <div class="magazin-card-author">By: @Model.AuthoredBy </div>
            </div>
    </a>
</div>

BMS-dotnet-WebApplication/Views/Shared/_miniContentCart.cshtml
@model BMS_dotnet_WebApplication.Models.MagazineVM.OtherContent
@{
    ViewData["Title"] = "_MagazineCard";
}

<div class="card-Magazine-mini" >
    <a href='@Url.Action("Details","Magazine",new { Id = Model.Id,mid= Model.MagazineId })'>
        <img style=" max-height: 60px;" src="@Url.Action("GetImage", new {filename = $"{Model.FolderName}/{Model.Image}", section = "magazine"})" alt="...">
        <br />
        @if (Model.Heading.Length > 21)
        {
            <span style=" font-size: 10px;">@Model.Heading.Substring(0, 20) ...</span>
        }
        else
        {
            <span style=" font-size: 10px;">@Model.Heading ...</span>
        }

    </a>
   
</div>

BMS-dotnet-WebApplication/Views/Shared/_quilljsTextEditor.cshtml
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>